server:
  port: 443  # Required by Hugging Face / Container Port
  address: 0.0.0.0
lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.11.5" # Essential YouTube source support for Lavalink v4
      repository: "https://maven.lavalink.dev/releases"
  server:
    password: "youshallnotpass" # Your secure password
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: false
      vimeo: false
      http: true
      local: false
    filters:
      volume: true
      equalizer: true
      timescale: true
      karaoke: true
      channelMix: true
      distortion: true
      rotation: true
      lowPass: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: HIGH
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

logging:
  file:
    max-history: 30
    max-size: 1GB
  path: ./logs/
  level:
    root: INFO
    lavalink: INFO

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoLoop: true
    allowDirectPlaylistLoop: true
    clients:
      - MUSIC
      - ANDROID_VR
      - WEB
      - WEBEMBEDDED
      - ANDROID_MUSIC
      - ANDROID
      - TVHTML5
      - IOS
    oauth:
      enabled: true
